//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace saafcity_fyp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public string User_ID { get; set; }
        public string Password { get; set; }
        public Nullable<int> Employee_Id { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
